### ISSUE TITLE
DevOps AWS

### ISSUE THREAD

**Issue by andreareginato** [lelylan/lelylan#137]
Use the main repo `lelylan/lelylan` as the repository to deploy the whole architecture on AWS and to setup the development environment. 

Suggested technologies:
- [Docker](http://docker.com/)
- [Ansible](http://ansible.com)

This should solve also the "problem" which makes people think that this is just a documentation repo (as there is no code to look at).

**Comment by boonpin1975** [comment]
May I suggest to use Vagrant ? I am looking to install the whole Lelylan microservice in my machine ...

**Comment by andreareginato** [comment]
HI @boonpin1975, thanks for writing!

Sure you can suggest Vagrant, as many other people are talking about it. Although I admit that looking on the web I can't get a clear idea of how (if it make sense) vagrant can be combined with Docker, or if it simply replace it. That said (i'm new to DevOps tools) I would love to see a working simplified solution to install Lelylan, and would be great to have someone experimenting in this part. 

In your opinion, which is the best way to mov forward with Vagrant?

**Comment by boonpin1975** [comment]
hi Andrea

 recently I have some chance to play with some open source IOT stack from
servioticy , they have some vagrant support ,with some puppet for
configuration management and post installation ...
https://github.com/servioticy/servioticy-vagrant , basically it need
virtual box on the local machine installed

thanks

**Comment by andreareginato** [comment]
I just checked the servioticy @boonpin1975 and I don't know how much you are involved, but it looks a nice project with nice docs and getting started for the IoT. If you are going to install all the microservices in your machine and you want to use Vagrant, it would be a great plus compared to today solution.

I read something today about and I'm in. Let me know how you would love to proceed on this.

**Comment by boonpin1975** [comment]
Currently I am doing evaluation on open source and commercial IOT
middleware. I would like to compare features available,ease of deployment,
so I think to speed up the deployment, valgrant/docker is a good idea

**Comment by andreareginato** [comment]
It sounds a valuable research. Le me know how things go with Lelylan and if I can help. 

I also would love to make one question. Are you going to publish your research about open source and commercial IoT solutions? I think people would find useful to have such a comparison to better understand what to choose.

**Comment by boonpin1975** [comment]
hi Andrea ,

  I am having some issue on building a local Lelylan micro service at my
machine .

  I have git clone all the required software from github .

  sorry to inform you that I am not able to publish the report , since it's
for internal reference but our research on the IOT middleware is based on
following


   -  protocol supported ( e.g. coap , mqtt , rest , stomp etc )
   -  SDK availability ( multiple language )
   -  low level field protocol wrapper supported  ( e.g. i2c , spi . uart ,
   gpio )  [ something like  MRAA/UPM  , smartjs , viperize IOT ]
   - private cloud solution vs SAAS [ some IOT suite might need to use
   their could solution ]
   - analytic engine
   - licencing
   - pricing
   - customization support
   - embedded system integration for low power MCU

thanks !

**Comment by andreareginato** [comment]
HI @boonpin1975. Thanks a lot for sharing your parameters.

Would you mind to open a new issue, describing which one is the service having problems and sharing with me the eventual error? Thanks

**Comment by evectis** [comment]
IMHO, from a container perspective of deploying the whole architecture, Docker support is essential today (the Docker image format is a de facto standard), although, in the long run, OCI (Open Container Initiative) container image support is the way to go.

**Comment by andreareginato** [comment]
Closing this issue. 

There is a whole refactoring to make Lelylan work with Docker thanks to @FedeG.
Feel free to reopen the issue if needed.
